services:
  ruvarr:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - path: .env
        required: false
    volumes:
      - ruvarr-data:/app/data
      # - /path/to/downloads:/downloads

volumes:
  ruvarr-data:
