services:
  ruvarr:
    user: "0:0"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - ./src/Ruvarr/data:/app/data
      - C:/dev/ruvarr/downloads:/downloads
