<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="TMDbLib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ruvarr.Contracts\Ruvarr.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ruvarr.UnitTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="Ruvarr.IntegrationTests" />
    <InternalsVisibleTo Include="Ruvarr.Testing" />
  </ItemGroup>

</Project>