// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ruvarr;

#nullable disable

namespace Ruvarr.Migrations
{
    [DbContext(typeof(RuvarrDbContext))]
    [Migration("20260322144242_MoveDownloadFkToQueue")]
    partial class MoveDownloadFkToQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Ruvarr.Downloads.Domain.DownloadQueueItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Downloaded")
                        .HasColumnType("TEXT")
                        .HasColumnName("downloaded");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("episode_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.HasKey("id")
                        .HasName("pk_download_queue");

                    b.HasIndex("episode_id")
                        .HasDatabaseName("ix_download_queue_episode_id");

                    b.ToTable("download_queue", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.RuvEpisode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTime>("FirstRun")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_run");

                    b.Property<int>("LookupCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lookup_count");

                    b.Property<DateTime?>("Matched")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched");

                    b.Property<DateTime?>("NextLookup")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_lookup");

                    b.Property<string>("RuvId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("ruv_id")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .IsFixedLength(false);

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("uri")
                        .IsFixedLength(false);

                    b.Property<int>("program_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("program_id");

                    b.HasKey("id")
                        .HasName("pk_episodes");

                    b.HasIndex("RuvId")
                        .IsUnique()
                        .HasDatabaseName("ix_episodes_ruv_id");

                    b.HasIndex("program_id")
                        .HasDatabaseName("ix_episodes_program_id");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.RuvProgram", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel")
                        .IsFixedLength(false);

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("description")
                        .IsFixedLength(false);

                    b.Property<string>("ForeignName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("foreign_name")
                        .IsFixedLength(false);

                    b.Property<bool>("HasMissingEpisodes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_missing_episodes");

                    b.Property<bool>("HasMultipleEpisodes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_multiple_episodes");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_monitored");

                    b.Property<int>("LookupCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lookup_count");

                    b.Property<DateTime?>("Matched")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .IsFixedLength(false);

                    b.Property<DateTime?>("NextLookup")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_lookup");

                    b.Property<int>("RuvId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ruv_id");

                    b.Property<string>("Slug")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<int?>("movie_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movie_id");

                    b.Property<int?>("series_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("series_id");

                    b.HasKey("id")
                        .HasName("pk_programs");

                    b.HasIndex("RuvId")
                        .IsUnique()
                        .HasDatabaseName("ix_programs_ruv_id");

                    b.HasIndex("movie_id")
                        .HasDatabaseName("ix_programs_movie_id");

                    b.HasIndex("series_id")
                        .HasDatabaseName("ix_programs_series_id");

                    b.ToTable("programs", null, t =>
                        {
                            t.HasCheckConstraint("ck_programs_slug_format", "slug IS NULL OR slug GLOB '[a-z0-9-]*'");
                        });
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.TmdbMovie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .IsFixedLength(false);

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tmdb_id");

                    b.HasKey("id")
                        .HasName("pk_movies");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_movies_tmdb_id");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.TvdbEpisode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_number");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_missing");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.Property<int>("TvdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tvdb_id");

                    b.Property<int>("episode_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.HasKey("id")
                        .HasName("pk_tvdb_episodes");

                    b.HasIndex("episode_id", "TvdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_tvdb_episodes_episode_id_tvdb_id");

                    b.ToTable("tvdb_episodes", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.TvdbSeries", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .IsFixedLength(false);

                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug")
                        .IsFixedLength(false);

                    b.Property<int>("TvdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tvdb_id");

                    b.HasKey("id")
                        .HasName("pk_series");

                    b.HasIndex("TvdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_tvdb_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Downloads.Domain.DownloadQueueItem", b =>
                {
                    b.HasOne("Ruvarr.Programs.Domain.RuvEpisode", "Episode")
                        .WithMany("DownloadQueueItems")
                        .HasForeignKey("episode_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_download_queue_episodes_episode_id");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.RuvEpisode", b =>
                {
                    b.HasOne("Ruvarr.Programs.Domain.RuvProgram", "Program")
                        .WithMany("Episodes")
                        .HasForeignKey("program_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_programs_program_id");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.RuvProgram", b =>
                {
                    b.HasOne("Ruvarr.Programs.Domain.TmdbMovie", "Movie")
                        .WithMany("Programs")
                        .HasForeignKey("movie_id")
                        .HasConstraintName("fk_programs_movies_movie_id");

                    b.HasOne("Ruvarr.Programs.Domain.TvdbSeries", "Series")
                        .WithMany("Programs")
                        .HasForeignKey("series_id")
                        .HasConstraintName("fk_programs_series_series_id");

                    b.Navigation("Movie");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.TvdbEpisode", b =>
                {
                    b.HasOne("Ruvarr.Programs.Domain.RuvEpisode", null)
                        .WithMany("TvdbEpisodes")
                        .HasForeignKey("episode_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tvdb_episodes_episodes_episode_id");
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.RuvEpisode", b =>
                {
                    b.Navigation("DownloadQueueItems");

                    b.Navigation("TvdbEpisodes");
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.RuvProgram", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.TmdbMovie", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("Ruvarr.Programs.Domain.TvdbSeries", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
