// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ruvarr;

#nullable disable

namespace Ruvarr.Migrations
{
    [DbContext(typeof(RuvarrDbContext))]
    [Migration("20260311152014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("Ruvarr.Downloads.Domain.DownloadQueueItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Downloaded")
                        .HasColumnType("TEXT")
                        .HasColumnName("downloaded");

                    b.HasKey("id")
                        .HasName("pk_download_queue");

                    b.ToTable("download_queue", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Ruv.Domain.RuvEpisode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_number");

                    b.Property<DateTime>("FirstRun")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_run");

                    b.Property<int>("LookupCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lookup_count");

                    b.Property<DateTime?>("Matched")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched");

                    b.Property<DateTime?>("NextLookup")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_lookup");

                    b.Property<string>("RuvId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("ruv_id")
                        .IsFixedLength();

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .IsFixedLength(false);

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tvdb_id");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("uri")
                        .IsFixedLength(false);

                    b.Property<int?>("download_queue_item_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("download_queue_item_id");

                    b.Property<int>("program_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("program_id");

                    b.HasKey("id")
                        .HasName("pk_episodes");

                    b.HasIndex("RuvId")
                        .IsUnique()
                        .HasDatabaseName("ix_episodes_ruv_id");

                    b.HasIndex("download_queue_item_id")
                        .IsUnique()
                        .HasDatabaseName("ix_episodes_download_queue_item_id");

                    b.HasIndex("program_id")
                        .HasDatabaseName("ix_episodes_program_id");

                    b.ToTable("episodes", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Ruv.Domain.RuvProgram", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel")
                        .IsFixedLength(false);

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("ForeignName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("foreign_name")
                        .IsFixedLength(false);

                    b.Property<bool>("HasMultipleEpisodes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_multiple_episodes");

                    b.Property<int>("LookupCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lookup_count");

                    b.Property<DateTime?>("Matched")
                        .HasColumnType("TEXT")
                        .HasColumnName("matched");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .IsFixedLength(false);

                    b.Property<DateTime?>("NextLookup")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_lookup");

                    b.Property<int>("RuvId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ruv_id");

                    b.Property<int?>("movie_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movie_id");

                    b.Property<int?>("series_id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("series_id");

                    b.HasKey("id")
                        .HasName("pk_programs");

                    b.HasIndex("RuvId")
                        .IsUnique()
                        .HasDatabaseName("ix_programs_ruv_id");

                    b.HasIndex("movie_id")
                        .HasDatabaseName("ix_programs_movie_id");

                    b.HasIndex("series_id")
                        .HasDatabaseName("ix_programs_series_id");

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Tmdb.Domain.TmdbMovie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .IsFixedLength(false);

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tmdb_id");

                    b.HasKey("id")
                        .HasName("pk_movies");

                    b.HasIndex("TmdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_movies_tmdb_id");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Tvdb.Domain.TvdbSeries", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .IsFixedLength(false);

                    b.Property<string>("TvdbId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("tvdb_id")
                        .IsFixedLength(false);

                    b.HasKey("id")
                        .HasName("pk_series");

                    b.HasIndex("TvdbId")
                        .IsUnique()
                        .HasDatabaseName("ix_series_tvdb_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Ruvarr.Ruv.Domain.RuvEpisode", b =>
                {
                    b.HasOne("Ruvarr.Downloads.Domain.DownloadQueueItem", "DownloadQueueItem")
                        .WithOne("Episode")
                        .HasForeignKey("Ruvarr.Ruv.Domain.RuvEpisode", "download_queue_item_id")
                        .HasConstraintName("fk_episodes_download_queue_download_queue_item_id");

                    b.HasOne("Ruvarr.Ruv.Domain.RuvProgram", "Program")
                        .WithMany("Episodes")
                        .HasForeignKey("program_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_programs_program_id");

                    b.Navigation("DownloadQueueItem");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Ruvarr.Ruv.Domain.RuvProgram", b =>
                {
                    b.HasOne("Ruvarr.Tmdb.Domain.TmdbMovie", "Movie")
                        .WithMany("Programs")
                        .HasForeignKey("movie_id")
                        .HasConstraintName("fk_programs_movies_movie_id");

                    b.HasOne("Ruvarr.Tvdb.Domain.TvdbSeries", "Series")
                        .WithMany("Programs")
                        .HasForeignKey("series_id")
                        .HasConstraintName("fk_programs_series_series_id");

                    b.Navigation("Movie");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Ruvarr.Downloads.Domain.DownloadQueueItem", b =>
                {
                    b.Navigation("Episode")
                        .IsRequired();
                });

            modelBuilder.Entity("Ruvarr.Ruv.Domain.RuvProgram", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Ruvarr.Tmdb.Domain.TmdbMovie", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("Ruvarr.Tvdb.Domain.TvdbSeries", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
